#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Brings steam-infra up from a clean `tofu destroy` state, in five stages:
#
#   1. Reset Snowflake — drop the sink's tables + Snowpipe Streaming pipes.
#                        Their committed channel offsets survive `tofu
#                        destroy`; with snapshot.mode=always the Kafka topics
#                        restart at offset 0 each session, so a stale offset
#                        makes the sink skip every record. Runs first, before
#                        any infra, so the bring-up is idempotent.
#   2. Infra          — one `tofu apply`: network, RDS, bastion, EKS, ECR,
#                        then the Strimzi operator.
#   3. Schema + seed   — schema.sql + seed.py through an SSM tunnel, so the
#                        generator never boots against an empty DB and the
#                        Debezium connector has its tables + grant.
#   4. CDC layer       — kubectl: Kafka cluster, Kafka Connect (in-cluster
#                        image build), Debezium source + Snowflake sink
#                        connectors.
#   5. Generator       — `tofu apply` for the generator (held back until seed
#                        data exists), then an end-to-end smoke test.
#
# Teardown is a separate flow: drop the Debezium replication slot
# (scripts/teardown-replication-slot.sh) *before* `tofu destroy`. The sink
# side is reset at Stage 1 above, not at teardown, so a skipped teardown
# can't wedge the next run.

TOTAL_STAGES=5

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"
VENV=/tmp/steam-infra-venv
SMOKE_VENV=/tmp/steam-infra-smoke-venv
AWS_REGION="${AWS_REGION:-us-east-1}"

# Python version the venvs are built with. The host default python3 floats
# with the OS and has run ahead of what the pinned requirements ship wheels
# for: on 3.14, snowflake-connector-python==3.12.3 and its capped cffi<2 fall
# back to sdist builds that need python3-dev + libffi-dev, so the smoke-test
# venv dies with "Python.h: No such file". ensure_venv pins this instead
# (via uv, which fetches it if missing; see there for the no-uv case).
VENV_PYTHON="${VENV_PYTHON:-3.12}"

# Snowflake RSA private key for the sink connector + smoke test. Lives
# outside the repo; override by exporting SNOWFLAKE_KEY_FILE before running.
SNOWFLAKE_KEY_FILE="${SNOWFLAKE_KEY_FILE:-$HOME/.dbt/snowflake_analytics_key.p8}"
export SNOWFLAKE_KEY_FILE

# RDS instance identifier — hardcoded in terraform/rds.tf (aws_db_instance.main).
RDS_INSTANCE_ID="steam-infra"

tf() { tofu -chdir="$TF_DIR" "$@"; }

# Logs from run_step live here (predictable path, survives the run).
LOG_DIR="${TMPDIR:-/tmp}/steam-infra-bootstrap"
mkdir -p "$LOG_DIR"

# run_step "label" CMD...  runs CMD with its output hidden. On success: one
# quiet line. On failure: the tail of its log, then exit. Keeps tofu apply
# noise off the screen without losing it when something breaks.
run_step() {
  local label="$1"; shift
  local slug log
  slug=$(printf '%s' "$label" | tr -cs 'a-zA-Z0-9' '-')
  log="$LOG_DIR/${slug%-}.log"
  if ! "$@" >"$log" 2>&1; then
    warn "$label failed — tail of $log:"
    tail -n 40 "$log" >&2
    exit 1
  fi
}

# Numbered sub-steps for Stage 1's two tofu applies. nstep prints "N. label";
# nsub / nbullet indent body lines to sit past the "N. " so nothing under a
# number lines up with it.
nstep()   { printf '\n  %s%s.%s %s\n' "$BOLD" "$1" "$RESET" "$2"; }
nsub()    { printf '     %s\n' "$1"; }
nbullet() { printf '     %s•%s %s\n' "$BLUE" "$RESET" "$1"; }

# ensure_venv DIR REQ_FILE  (re)creates DIR as a venv on Python $VENV_PYTHON
# and installs REQ_FILE into it.
#
# Prefers uv: it uses a matching interpreter already on the system, or fetches
# a standalone one (~100MB, cached in ~/.local/share/uv, downloaded once) when
# none is present — so the venv never depends on what the host's python3
# happens to be. Set UV_PYTHON_DOWNLOADS=never to forbid the fetch.
#
# Without uv, falls back to `pythonX.Y -m venv` and needs that exact
# interpreter on PATH (Debian/Ubuntu: apt install pythonX.Y pythonX.Y-venv);
# a missing pip in the fresh venv means the -venv package isn't installed.
ensure_venv() {
  local dir="$1" reqs="$2"
  rm -rf "$dir"
  if command -v uv >/dev/null 2>&1; then
    uv venv --python "$VENV_PYTHON" "$dir" >/dev/null
    uv pip install -q --python "$dir/bin/python" -r "$reqs"
    return
  fi
  local py="python${VENV_PYTHON}"
  command -v "$py" >/dev/null 2>&1 \
    || { warn "no uv, and $py not on PATH — install it (apt install $py ${py}-venv) or install uv"; exit 1; }
  "$py" -m venv "$dir" || { warn "$py -m venv failed — install ${py}-venv, then re-run"; exit 1; }
  [[ -x "$dir/bin/pip" ]] \
    || { warn "venv has no pip — Debian/Ubuntu split it out; run 'sudo apt install ${py}-venv' and re-run"; exit 1; }
  "$dir/bin/pip" install -q -r "$reqs"
}

_TUNNEL_PID=""
_TUNNEL_LOG=""

# Kill any SSM tunnel we opened (and the session-manager-plugin child that
# outlives the `aws` pid and keeps localPortNumber 15432 bound) on any exit.
cleanup() {
  [[ -n "$_TUNNEL_PID" ]] && kill "$_TUNNEL_PID" 2>/dev/null || true
  pkill -f "localPortNumber.*15432" 2>/dev/null || true
  [[ -n "$_TUNNEL_LOG" ]] && rm -f "$_TUNNEL_LOG" || true
}
trap cleanup EXIT

# open_rds_tunnel BASTION_ID RDS_HOST forwards localhost:15432 -> RDS:5432
# through the bastion over SSM (RDS has no public IP). Polls the SSM CLI's own
# "Waiting for connections" line rather than sleeping a fixed amount.
open_rds_tunnel() {
  local bastion_id="$1" rds_host="$2" i
  # Clear any session-manager-plugin still holding port 15432 from an earlier
  # tunnel — the helper scripts we call (check-rds-prereqs.sh) don't kill
  # their own plugin child, only the `aws` parent.
  pkill -f "localPortNumber.*15432" 2>/dev/null || true
  _TUNNEL_LOG=$(mktemp)
  aws ssm start-session --target "$bastion_id" \
    --document-name AWS-StartPortForwardingSessionToRemoteHost \
    --parameters "{\"host\":[\"$rds_host\"],\"portNumber\":[\"5432\"],\"localPortNumber\":[\"15432\"]}" \
    >"$_TUNNEL_LOG" 2>&1 &
  _TUNNEL_PID=$!
  for i in $(seq 1 30); do
    grep -q "Waiting for connections" "$_TUNNEL_LOG" && return 0
    if ! kill -0 "$_TUNNEL_PID" 2>/dev/null; then
      warn "SSM session exited before the tunnel opened:"
      cat "$_TUNNEL_LOG" >&2
      return 1
    fi
    sleep 1
  done
  warn "tunnel never came up:"
  cat "$_TUNNEL_LOG" >&2
  return 1
}

close_rds_tunnel() {
  [[ -n "$_TUNNEL_PID" ]] && kill "$_TUNNEL_PID" 2>/dev/null || true
  pkill -f "localPortNumber.*15432" 2>/dev/null || true
  [[ -n "$_TUNNEL_LOG" ]] && rm -f "$_TUNNEL_LOG"
  _TUNNEL_PID=""
  _TUNNEL_LOG=""
}

banner "steam-infra bring-up"

# ── preflight: fail before an hour of provisioning, not during ────────────
_missing=()
for _bin in tofu aws kubectl psql jq python3 session-manager-plugin; do
  command -v "$_bin" >/dev/null 2>&1 || _missing+=("$_bin")
done
if (( ${#_missing[@]} )); then
  warn "missing required tools: ${_missing[*]}"
  note "  kubectl                → https://kubernetes.io/docs/tasks/tools/"
  note "  psql                   → apt install postgresql-client   (or brew install libpq)"
  note "  session-manager-plugin → https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html"
  exit 1
fi
if [[ ! -f "$SNOWFLAKE_KEY_FILE" ]]; then
  warn "Snowflake private key not found: $SNOWFLAKE_KEY_FILE"
  note "place it there, or export SNOWFLAKE_KEY_FILE=<path>, then re-run."
  exit 1
fi
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  warn "AWS credentials not working (aws sts get-caller-identity failed)."
  note "configure your AWS profile / SSO session, then re-run."
  exit 1
fi
say "preflight OK — tools, Snowflake key, AWS creds all present."
pause "Start the bring-up?"

# ── Stage 1: reset Snowflake sink state ──────────────────────────────────
stage "Reset Snowflake sink state"
say "Snowpipe Streaming channels and their committed offsets live in"
say "Snowflake and survive 'tofu destroy'. snapshot.mode=always restarts the"
say "Kafka topics at offset 0 every session, so a leftover channel offset"
say "makes the sink skip every record — 0 rows in Snowflake, smoke test fails."
say "Dropping the sink's tables + pipes now lets Stage 4 recreate them clean."
say ""

nstep 1 "building the venv for the Snowflake client..."
ensure_venv "$SMOKE_VENV" "$REPO_ROOT/scripts/requirements-smoke-test.txt"

nstep 2 "dropping sink tables + Snowpipe Streaming pipes (idempotent)..."
"$SMOKE_VENV/bin/python" "$REPO_ROOT/scripts/reset-snowflake-sink.py"

say ""
printf '  %s✓%s snowflake sink state clean\n' "$GREEN" "$RESET"
pause "Continue to infra?"

# ── Stage 2: infra ───────────────────────────────────────────────────────
stage "Infra"
say "One 'tofu apply'. EKS node groups are the slow part — budget 15-20 min."
say "Nothing runs on the cluster yet."

run_step "tofu init" tf init -input=false

# -exclude, not -target: -target only pulls in resources the target
# references by a read attribute and silently drops siblings nothing points
# at (bit twice — the bastion_ssm attachment, then the IGW + route table).
# -exclude applies the whole config minus the named resource instead.
#   - the generator is held back until seed data exists (Stage 2)
#   - Strimzi is split into its own apply so a helm/exec-auth hiccup against
#     the brand-new cluster doesn't force re-planning the whole stack
nstep 1 "applying core infra (this is the slow one)..."
nsub ""
nsub "bringing up:"
nbullet "core network resources (VPC, subnets, routes, IGW)"
nbullet "rds instance (postgres)"
nbullet "bastion EC2 instance"
nbullet "EKS nodes (system + kafka node groups)"
nbullet "empty ECR repo for the Kafka Connect image"
run_step "tofu apply core" \
  tf apply -auto-approve -exclude=aws_instance.generator -exclude=helm_release.strimzi

nstep 2 "applying strimzi operator to the EKS cluster..."
run_step "tofu apply strimzi" tf apply -auto-approve -exclude=aws_instance.generator

say ""
printf '  %s✓%s infra up!\n' "$GREEN" "$RESET"
pause "Continue to schema + seed?"

# ── Stage 3: schema + seed ───────────────────────────────────────────────
stage "Schema + seed"
say "The generator crash-loops against empty users/games; the Debezium"
say "connector needs the schema + rds_replication grant. Both land here."

BASTION_ID=$(tf output -raw bastion_instance_id)
RDS_HOST=$(tf output -raw rds_endpoint)

# 1. The bastion EC2 instance is freshly booted; its SSM agent registers with
#    the Systems Manager service a minute or two *after* the instance reaches
#    "running". Until PingStatus is "Online", start-session fails with
#    TargetNotConnected, so poll for it:
#      aws ssm describe-instance-information \
#        --filters Key=InstanceIds,Values=<bastion> \
#        --query 'InstanceInformationList[0].PingStatus'
nstep 1 "waiting for the bastion SSM agent to register with SSM..."
PING_STATUS=""
for _ in $(seq 1 40); do
  PING_STATUS=$(aws ssm describe-instance-information \
    --filters "Key=InstanceIds,Values=$BASTION_ID" \
    --query 'InstanceInformationList[0].PingStatus' --output text 2>/dev/null || true)
  [[ "$PING_STATUS" == "Online" ]] && break
  sleep 5
done
[[ "$PING_STATUS" == "Online" ]] || { warn "bastion SSM agent never came online"; exit 1; }

# 2. RDS has no public IP and only accepts Postgres from the bastion/generator/
#    EKS security groups, so schema.sql and seed.py (run locally) reach it
#    through an SSM Session Manager port-forward: localhost:15432 -> bastion ->
#    RDS:5432, backgrounded.
#      aws ssm start-session --target <bastion> \
#        --document-name AWS-StartPortForwardingSessionToRemoteHost \
#        --parameters '{"host":["<rds>"],"portNumber":["5432"],"localPortNumber":["15432"]}'
nstep 2 "opening SSM tunnel to RDS through the bastion..."
open_rds_tunnel "$BASTION_ID" "$RDS_HOST" || exit 1

nstep 3 "creating python venv and installing requirements.txt..."
ensure_venv "$VENV" "$REPO_ROOT/generator/requirements.txt"

# Same DB_* vars seed.py and the generator read, pointed at the tunnel.
export DB_HOST=localhost DB_PORT=15432 DB_NAME=steam DB_USER=steam_proj_admin
DB_PASSWORD=$(tf output -raw db_password)
export DB_PASSWORD

# schema.sql is plain DDL and seed.py is plain INSERTs — neither is safe to
# re-run. The guard applies the schema only if absent and reports, by exit
# code, whether seed is still needed: 0 = applied fresh, 3 = already there
# but users empty, 4 = already there with rows (skip seed).
nstep 4 "applying schema to rds..."
schema_rc=0
"$VENV/bin/python" - "$REPO_ROOT/db/schema.sql" <<'PY' || schema_rc=$?
import os, sys, psycopg2
conn = psycopg2.connect(
    host=os.environ["DB_HOST"], port=os.environ["DB_PORT"],
    dbname=os.environ["DB_NAME"], user=os.environ["DB_USER"],
    password=os.environ["DB_PASSWORD"],
)
with conn, conn.cursor() as cur:
    cur.execute("select to_regclass('public.users')")
    fresh = cur.fetchone()[0] is None
    if fresh:
        cur.execute(open(sys.argv[1]).read())
    cur.execute("select count(*) from users")
    n = cur.fetchone()[0]
conn.close()
sys.exit(0 if fresh else (3 if n == 0 else 4))
PY
case "$schema_rc" in
  0) ;;
  3|4) nbullet "skipping — schema already present" ;;
  *)   warn "schema check failed"; exit 1 ;;
esac

nstep 5 "seeding tables (users, games, game_prices)"
if [[ "$schema_rc" == 4 ]]; then
  nbullet "skipping — seed data already present"
else
  run_step "seed" "$VENV/bin/python" "$REPO_ROOT/generator/seed.py"
fi

say ""
say "closing tunnel..."
close_rds_tunnel
pause "Continue to the CDC layer?"

# ── Stage 4: CDC layer ───────────────────────────────────────────────────
stage "CDC layer — Kafka, Connect, connectors"
say "All applied with kubectl. The Strimzi operator turns these specs into"
say "running pods."
say ""

nstep 1 "updating kubeconfig to point at the EKS cluster..."
aws eks update-kubeconfig --name steam-infra --region "$AWS_REGION" >/dev/null

nstep 2 "starting RDS pre-checks..."
nsub ""
nbullet "does postgres have WAL enabled for CDC?"
nbullet "has steam_proj_admin been granted the rds_replication role?"
nbullet "does steam_proj_admin have SELECT on all 16 tables?"
_prereq_rc=0
_prereq_out=$("$REPO_ROOT/scripts/check-rds-prereqs.sh" 2>&1) || _prereq_rc=$?
if (( _prereq_rc != 0 )); then
  printf '%s\n' "$_prereq_out"
  if grep -q 'wal_level=' <<<"$_prereq_out" && grep -q 'expected logical' <<<"$_prereq_out"; then
    warn "wal_level is not 'logical' — rds.logical_replication needs a reboot to take effect."
    if confirm "reboot RDS instance '$RDS_INSTANCE_ID' now and wait for it?"; then
      aws rds reboot-db-instance --db-instance-identifier "$RDS_INSTANCE_ID" >/dev/null
      say "waiting for RDS to come back..."
      aws rds wait db-instance-available --db-instance-identifier "$RDS_INSTANCE_ID"
      say "re-checking prerequisites..."
      "$REPO_ROOT/scripts/check-rds-prereqs.sh"
    else
      warn "skipped reboot — the Debezium connector will fail until wal_level=logical."
      exit 1
    fi
  else
    warn "RDS prerequisites failed for a reason the wizard won't auto-fix (see above)."
    exit 1
  fi
fi

say ""
printf '     %s✓%s rds pre-checks are good!\n' "$GREEN" "$RESET"

say "applying strimzi kafka dual-role's yaml..."
kubectl apply -f "$REPO_ROOT/k8s/kafka/kafka-cluster.yaml"
say "waiting for the Kafka cluster to be Ready (3 brokers, a few minutes)..."
kubectl wait kafka/steam-infra -n kafka --for=condition=Ready --timeout=600s

say "building Kafka Connect image (in-cluster Maven build + ECR push, 5-10 min)..."
ECR_REPO=$(tf output -raw kafka_connect_ecr_repository_url)
kubectl create secret docker-registry ecr-registry-credentials -n kafka \
  --docker-server="${ECR_REPO%%/*}" \
  --docker-username=AWS \
  --docker-password="$(aws ecr get-login-password --region "$AWS_REGION")" \
  --dry-run=client -o yaml | kubectl apply -f -
sed "s|<account-id>.dkr.ecr.us-east-1.amazonaws.com/steam-infra-kafka-connect|$ECR_REPO|" \
  "$REPO_ROOT/k8s/kafka/kafka-connect.yaml" | kubectl apply -f -
kubectl wait kafkaconnect/steam-infra -n kafka --for=condition=Ready --timeout=900s

say "wiring connector secrets (rds-credentials, snowflake-keypair)..."
"$REPO_ROOT/scripts/create-connector-secrets.sh"

say "applying Debezium source connector yaml..."
sed "s|<rds-endpoint>|$(tf output -raw rds_endpoint)|" \
  "$REPO_ROOT/k8s/kafka/debezium-connector.yaml" | kubectl apply -f -

say "applying Snowflake sink connector yaml..."
kubectl apply -f "$REPO_ROOT/k8s/kafka/snowflake-connector.yaml"

say "verifying connector health (retrying while they reach RUNNING)..."
_health_ok=""
for _ in $(seq 1 10); do
  if "$REPO_ROOT/scripts/check-connector-health.sh"; then _health_ok=1; break; fi
  sleep 15
done
[[ -n "$_health_ok" ]] || { warn "connectors did not all reach RUNNING"; exit 1; }
pause "Continue to the generator + smoke test?"

# ── Stage 5: generator + smoke test ──────────────────────────────────────
stage "Generator + end-to-end smoke test"
say "The generator is applied last so it only ever boots against a seeded DB."
say ""

say "starting the generator..."
run_step "tofu apply generator" tf apply -auto-approve

say "opening SSM tunnel for the smoke test..."
BASTION_ID=$(tf output -raw bastion_instance_id)
RDS_HOST=$(tf output -raw rds_endpoint)
open_rds_tunnel "$BASTION_ID" "$RDS_HOST" || exit 1

say "preparing smoke-test venv..."
ensure_venv "$SMOKE_VENV" "$REPO_ROOT/scripts/requirements-smoke-test.txt"

say "running end-to-end smoke test (RDS write → Debezium → Kafka → Snowflake)..."
DB_HOST=localhost DB_PORT=15432 DB_NAME=steam DB_USER=steam_proj_admin \
DB_PASSWORD="$(tf output -raw db_password)" \
"$SMOKE_VENV/bin/python" "$REPO_ROOT/scripts/smoke-test.py"

close_rds_tunnel

finish
say "generator is running and ticking. Between sessions, stop the metered"
say "resources (EKS is the expensive one — a full 'tofu destroy' is the reset):"
note "  aws ec2 stop-instances --instance-ids \$(tofu -chdir=terraform output -raw generator_instance_id)"
note "  aws rds stop-db-instance --db-instance-identifier steam-infra"
say "Teardown: run scripts/teardown-replication-slot.sh BEFORE 'tofu destroy'."
note "  (the Snowflake sink is reset at Stage 1 of the next bring-up, not here)"
