apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.22.0
      helm:
        valueFiles:
          - $values/k8s/airflow/values.yaml
          - $values/k8s/airflow/values-image.yaml
    - repoURL: https://github.com/Dulain-Willis/steam-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
