apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dulain-Willis/steam-infra.git
    targetRevision: main
    path: k8s/strimzi-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
